Add readme file and data base setup
Divinity-dev/Vet_clinic pull request #1
Opened 2023-04-03 22:32 UTC by Divinity-dev

In this phase of the project, I have accomplished the following;
1. created a database for a vet store which includes id, name, date_of-birth, neutered, escape_attempts, and weight.
2. I have succeeded in filling the various data fields.
3. I have also implemented a search filter which includes;
 Find  animals whose name ends with "mon"
<img width="542" alt="mon" src="https://user-images.githubusercontent.com/102070638/229639587-3fffffe3-686a-4acf-a42c-f5db4ed0ca93.png">
Find animals born between 2016 and 2019.
<img width="532" alt="btw" src="https://user-images.githubusercontent.com/102070638/229639758-1210251e-70f1-49e8-945a-4139d826c4e1.png">
Find animals that are neutered and have less than 3 escape attempts.
<img width="169" alt="neutered" src="https://user-images.githubusercontent.com/102070638/229640535-f9266f18-0a49-4f5e-98f6-fed7896d9ddc.png">
Find animals named either "Agumon" or "Pikachu".
<img width="122" alt="dob" src="https://user-images.githubusercontent.com/102070638/229640707-1c5b0f4e-3937-46f0-a830-c8899b04c912.png">
List name and escape attempts of animals that weigh more than 10.5kg
<img width="258" alt="escape" src="https://user-images.githubusercontent.com/102070638/229640841-99d58a17-19fc-45f7-82dc-5501183f776a.png">
Find all animals that are neutered.
<img width="531" alt="All data" src="https://user-images.githubusercontent.com/102070638/229640984-ab2232db-7965-4dcf-a24a-3f517bfa66d6.png">
Find all animals not named Gabumon.
<img width="532" alt="all data2" src="https://user-images.githubusercontent.com/102070638/229641042-bae1dbd9-3e25-4218-b4c4-0d01abbbd60c.png">
Find all animals with a weight between 10.4kg and 17.3kg 
<img width="536" alt="all data3" src="https://user-images.githubusercontent.com/102070638/229641191-db191b29-1677-4fe9-8392-2d7cf622e7eb.png">

2023-04-03 22:44 UTC, alexander16108 requested changes
Hi @Divinity-dev , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/rXBt6OIYwMFzU5Il8c/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Required Changes ♻️
_Check the comments under the review._

- [ ] as seen in the screenshot your entries are in duplicates please fix this and submit the new and updated screenshots

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-03 22:44 UTC, alexander16108 commented on README.md
> +- [Live Demo Link](https://google.com)
remove the live demo link because it is irrelevant and serves no purpose 👍🏾

2023-04-03 22:44 UTC, alexander16108 commented on data.sql
> +VALUES('Devimon', '2017-05-12', 5, true, 11);
as seen in the queries the weight entry should be a float number and not a whole number as u represented above 👍🏾 please change it and put in the right entries

2023-04-04 09:04 UTC, emmanuellekamwa approved these changes
**STATUS: APPROVED 🍾✔🎉**
Hello @Divinity-dev 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- You documented your work professionally.✔
- Good job implementing the requested changes.
- Your linters are passing all the checks.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-04 09:05 UTC, Divinity-dev commented
Thank you 

Sent from Yahoo Mail on Android 
 
  On Tue, Apr 4, 2023 at 10:04 AM, Kamwa Emmanuelle ***@***.***> wrote:   


@emmanuellekamwa approved this pull request.

STATUS: APPROVED 🍾 ✔ 🎉
Hello @Divinity-dev 👋
Your project is complete! There is nothing else to say other than... it's time to merge it 
Congratulations! 🎉
 
Highlights
   
   - You documented your work professionally. ✔
   - Good job implementing the requested changes.
   - Your linters are passing all the checks.

Cheers and Happy coding! 👏 👏 👏
 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

As described in the Code reviews limits policy you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this form.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-04-04 11:49 UTC, merged